### ISSUE TITLE
whoami command changes + move to userinfo endpoint

### ISSUE THREAD

**Issue by corpulentcoffee** [globus/globus-cli#115]
- [ ] change the backing API from the Auth `whoami` endpoint to the future Auth `userinfo` endpoint
     requires auth:view_identity_set scope
- [ ] add support for returning the linked identities (which may require requesting an additional scope for those to be returned via the `userinfo` Auth API endpoint)

**Comment by sirosen** [comment]
Updated name to clarify. Also, a bit of a bump.

I'll open an SDK issue for userinfo support and reference this. Considering it still blocked on implementation/release of that feature.

**Comment by sirosen** [comment]
This is no longer blocked on SDK support for userinfo, but we'd need to add a scope to logins.

We could add `urn:globus:auth:scope:auth.globus.org:view_identity_set` to our requested scopes and not use it, but there's no way to start using this without being backwards incompatible.

I'm marking this as a breaking change for CLI v2.

**Comment by sirosen** [comment]
Per discussion in Slack, we found a nice way to move forward.

- Use userinfo for `globus whoami`
- Update the tokens requested to include `view_identity_set`
- `globus whoami --linked-identities` will attempt to fetch linked IDs. If it fails due to the missing scope, prompt the user with a UsageError about needing a fresh login
