### ISSUE TITLE
'globus endpoint search' help message

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#140]
I typed 'globus endpoint search', expecting to get a helpful usage message, but instead got an error:

$ globus endpoint search
Globus CLI Error: A Transfer API Error Occurred.
HTTP status:      400
request_id:       B1eYyBvVj
code:             BadRequest
message:          scope 'all' requires an additional filter parameter

**Comment by sirosen** [comment]
This should definitely should be a `UsageError`

@tuecke By way of explanation, the "fulltext filter" is an optional positional parameter, to allow for things like `globus endpoint search --filter-scope administered-by-me`.

I think we should just change this so that if the filter-scope is `all` (default), then the parameter is treated as required.
That will also cover `globus endpoint search --filter-scope all`, which is also invalid.

Implementation-wise, this is method-body validation -- we can't conditionally set `required=True` on an option because we wouldn't know what to set it to until parse-time.

**Comment by jaswilli** [comment]
> Implementation-wise, this is method-body validation -- we can't conditionally set required=True on an option because we wouldn't know what to set it to until parse-time.

I looked around to see if there was some clever way to do this but like you said above, doing an inline validation seems to be the best bet.
