### ISSUE TITLE
`globus login` doesn't know when the user is already logged in

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#153]
If the CLI already has valid tokens for the user, then "globus login" should just inmediately return success and "Already logged in".  Perhaps add a flag force re-login.

**Comment by sirosen** [comment]
I'm thinking about whether or not we should try to check the validity of the tokens.

It's obviously nice for the client to detect bad tokens and prompt for replacement in that specific case.
However, native apps can't use introspect, and under globus/globus-sdk-python#97 we discussed the fact that the token validation call isn't meant for clients to use at all, but for resource servers. If we think of Native Apps which want to check on their token validity as a valid and necessary use-case for that call, then that would be the best bet.

Barring some change to give us a long-term supported path for native apps to check validity (either a change in introspect or in our thinking about validate, since we don't want to use a call that may stop working in the future), not checking and assuming any tokens seen are valid seems best.

**Comment by tuecke** [comment]
Assuming tokens are valid seems reasonable.

Note that if some other globus cli command finds that a token is invalid, in addition to giving a reasonable response to the user, we should also do something to make sure the next "globus login" will not see the token and assume its valid.  Either delete the token, or set some flag to indicate it is invalid.

**Comment by sirosen** [comment]
If we feel comfortable saying that any `401` response means that the token is invalid, we could probably do that in the handling for `GlobusAPIError`s.
I'd opt for deleting tokens -- the logic is simpler and the users won't see a difference.

**Comment by jaswilli** [comment]
I'd be completely comfortable using `/v2/oauth2/token/validate` to check token status. I don't get the reasoning behind saying clients shouldn't be checking status. Clearly they don't need to do it before every API call just to avoid a `401`, but for things like `globus login` it seems way more reasonable than making throwaway API calls to every service.

> If we feel comfortable saying that any 401 response means that the token is invalid

Yeah a `401` should be an automatic re-auth. If we want to do this I suppose we need to do token invalidation on every token we have and then force a re-auth.

**Comment by mattias-lidman** [comment]
> I don't get the reasoning behind saying clients shouldn't be checking status.

We want to avoid client devs constantly checking token validity (producing load for us, latency for their users, and more complicated code for themselves) for no real benefit because what really matters is whether a particular RS will honor a token. I also think it's also a simpler mental model for devs coming new to the system.

But it's certainly not a hard rule and I'm fine with doing it in this case. In theory it could produce issues stemming from Auth and a RS having different ideas about token validity (e.g, RS decides to reject tokens with < 2 hrs left on their lifetime because of #internalpolicy) but for the narrow set of well known services the CLI uses that's unlikely to be a real problem.

(I still have reservations about adding a utility function to the SDK as per globus/globus-sdk-python#97 though)
