### ISSUE TITLE
A format option for transfer/delete that outputs only a task-ID (for pipelining)

### ISSUE THREAD

**Issue by aaschaer** [globus/globus-cli#157]
It would be nice to be able to write something like:

globus transfer ~/path ~/path -F task | globus task wait

**Comment by sirosen** [comment]
To do this, we need to decide on an implementation path that makes sense.
There are some nuances around format handling, the way it's currently built.

I'd prefer to think of this as general "shell-scripting friendly" output, rather than "task formatted output", just to avoid having many formats when some other command has a similar need.
So I'd call this format "shell".

The [definition of the format option](https://github.com/globus/globus-cli/blob/master/globus_cli/parsing/command_state.py#L31-L44) is already wrapped up in a helper that applies to every command.
The simplest approach is probably to add an optional argument to that helper to add additional formats, and pass it `add_formats=[SHELL_FORMAT]` when it gets attached to these commands.
However, the result is that you could do `globus transfer --format shell` but not `globus --format shell transfer` -- because `globus` is a command in its own right, with a different instance of the `--format` option.
That seems bad/confusing, as it means that the behavior of `--format` depends on where in the command it's placed.

After a bit of spelunking in the `click` codebase, it seems that `globus --format XYZ transfer` will process the `--format` argument with the following information:
- `globus` has been invoked -- it has an execution context and its options are known
- there is a subcommand to invoke, and _its name_ is "transfer"

That means that there hasn't been any processing of "the transfer command's `--format` option" yet.
So it hasn't had a chance to signal in any meaningful way that `--format` needs to accept more options.

One option is to do what shell completion does and walk the command tree, doing parsing along the way, and at each level check whether or not `--format` is modified. That seems very heavy handed for a small tweak, and it's highly error prone as we need to basically do "alternate universe parsing" and make sure we're not messing up the real parsing that will happen just afterwards.

---

Is there another way of doing this that I'm missing? I'd like to think so.

Click eager options don't solve it -- eagerness applies at a given level of the command hierarchy.

One thing we can do is wrap all `click.Command`s in a custom class of our own which makes `invoke()` check that the output format is valid and change the type of `--format` to not be `CaseInsensitiveChoice`.
This seems reasonable -- we're already using a custom class for the top-level `globus` `click.Group` command.
`--format` would work as it does today, but not enforce that the value is correct at the time that it is parsed.

**Comment by sirosen** [comment]
I forgot to do this, but a few days ago someone pointed out that this is a solved problem if we use `jmsepath`, as per #156.

Because that will make it possible to write a script which extracts that value, among many other things, I'm going to close this as a duplicate.
