### ISSUE TITLE
get-identities --map-http-status?

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#171]
What is the --map-http-status option on get-identiites?  What is the point of it?   Is it really needed?

If its really needed, can the -h help text for it be made shorter, so that its less dominating?  Perhaps just:

Map HTTP statuses to any of these exit codes: 0,1,50-99. E.g., "404=50,403=51"

**Comment by sirosen** [comment]
I think this option really needs some docs on the site, which it can refer back to.
Otherwise, I can't imagine anyone understanding what it does.

The intent is for that option to apply to every command which executes at least one request to the service. There might be a few cases where it's applied and not useful, but it's definitely needed on `get-identities`.

**Comment by tuecke** [comment]
Can we add options to get-identities to do whatever its needed for on that command, and remove it as a general option?

What I don't like about this option is that it causes the REST layer bleed through to the CLI in a big way.  Can we come up with a standard mapping of HTTP code to exit codes that we use throughout the CLI?  Then we can just document those exit codes with their meanings as a feature of the CLI, without users knowing or caring about the REST layer from which they originated.  For example, can we translate all of the 40x error codes to 4x?  Or 4xx to 40+xx?

**Comment by sirosen** [comment]
> Can we add options to get-identities to do whatever its needed for on that command, and remove it as a general option?

I think it applies less importantly on `get-identities` than it does on a lot of other commands.
For example, you can do a retry-safe endpoint deletion with
```
$ globus endpoint delete $EP_ID --map-http-status 404=0
```

> What I don't like about this option is that it causes the REST layer bleed through to the CLI in a big way.

Inevitably, API layer errors need to be propagated up somehow.
Their error codes are an essential piece of information to include, so that layer will have to bubble up somehow. This approach is very direct, and keeps us out of the way of knowledgeable users.

> Can we come up with a standard mapping of HTTP code to exit codes that we use throughout the CLI? ...

I understand that reaction, and it was my original perspective when Karl suggested a handling like this for the Transfer API `code` field. I couldn't follow through on his suggestion because not all of our APIs provide a `code` field, but it inspired this handling for HTTP statuses.

This approach has a few points of superiority over having an explicit mapping of our own.

- It reduces the need for prior knowledge to do correct error handling
- The textual representation of an error also accurately describes how to handle it
- The mapping is always explicit
- Multiple statuses may be mapped to the same exit code
- Mapping a status code back to success is easy, allowing scripts to `set -e` safely without needing `|| true` or other shenanigans

---

My big issue with this option is its overbearing helptext, which seems to also be the basis for this discussion. If we put together some proper docs that include examples, it could be trimmed down signfiicantly, but without that, it needs to be annoyingly noisy in `--help`.

**Comment by tuecke** [comment]
Map-http-status assumes that I understand how the CLI maps to REST API calls, which is not something I think we should be making people know.  Maybe as an advanced option, but even then you are saying that to be an advanced user of the CLI I must understand this mapping  to the REST API.  That just seems all wrong to me.

**Comment by sirosen** [comment]
This may need more discussion. Being able to correctly handle errors without parsing stderr is important, since stderr can never be guaranteed to be clean.
If we're okay with this option, at least for the foreseeable future, if we trim down its help text, that documentation change is probably the best path forward.

Whatever options we present for error handling should be consistent with the representation of errors which we produce on stderr. That way, after seeing an error a user is provided with the information necessary to handle it. The HTTP Status is part of our error output, so that constraint is met.

One option is to make this only available on Transfer-related operations and use the `code` field, i.e. `--map-error-code NotFound=0`, but that requires just as much familiarity with the API and is less generalizable.

I'm not aware of an available alternative approach for us to handle API errors.
We could have CLI-specific error codes which we use, but that would demand tremendous effort to document and maintain, and would not be at all future-proof as the APIs expand. In fact, that would likely result in the addition of a new API error breaking all existing versions of the CLI.

The current solution is robust enough to handle all current and future APIs uniformly, and provides a clear way of converting errors as rendered on stderr to usage patterns for handling those errors.
I am unaware of any superior solution for error handling.

**Comment by sirosen** [comment]
I'm removing the question label. I think the most reasonable thing we can do for v1 is to make the helptext much shorter. Going with the originally suggested text -- after consideration, it satisfies basic documentation needs and there's nothing obviously better.

As a follow up, it is possible for us to hide this option on all help except for top-level `globus --help`, but I don't know if that's necessary.
