### ISSUE TITLE
--format text output is inconsistent

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#180]
In some commands the text output is an ascii-art table.  (See #168 about changing this to --format table.)  For example:

$ globus bookmark list
Name                                | Endpoint ID                          | Bookmark ID                          | Path                               
----------------------------------- | ------------------------------------ | ------------------------------------ | -----------------------------------
midway/~/myproject                  | af7bda53-6d04-11e5-ba46-22000b92c6ec | d89d697e-8cce-11e5-9971-22000b96db58 | /~/myproject/                      

In some commands the text output is a set of Name:Value pairs, each on their own line.  For example:

$ globus bookmark show 13fddf3e-4e77-11e6-8235-22000b97daec
ID:          13fddf3e-4e77-11e6-8235-22000b97daec
Name:        My favorite project
Endpoint ID: af7bda53-6d04-11e5-ba46-22000b92c6ec
Path:        /~/myproject/

I assume the rule is that multi-record output uses the table format, where-as single-record output uses the Name:Value output.  I think we should be more consistent about this.

I suggest we name each of these output format distinctly: "--format table" vs "--format record".  For the record based output, if there are multiple output records, have a blank link between each record.

Note that record-based output should be consistent with aligning the value or not.  "globus bookmark show" aligns the values so that they all start at the same column.  But "globus whoami --verbose" does not, as it just has a single space between the : and the value.

**Comment by sirosen** [comment]
> Note that record-based output should be consistent with aligning the value or not. "globus bookmark show" aligns the values so that they all start at the same column. But "globus whoami --verbose" does not, as it just has a single space between the : and the value.

Yes, that was a bug in `whoami`. The fix will go out in the next CLI release.

> I assume the rule is that multi-record output uses the table format, where-as single-record output uses the Name:Value output. I think we should be more consistent about this.
>
> I suggest we name each of these output format distinctly: "--format table" vs "--format record". For the record based output, if there are multiple output records, have a blank link between each record.

Yes, tabular data is produced as a table, and single records are colon-delimited.

I don't see this behavior as inconsistent, and think that adding more formatting options only serves to confuse things and make more work for us.
The purpose of `--format TEXT` is to be free-form text data which we produce. It only needs to exist to describe non-`--format JSON` output.

If we have `--format TABLE` and `--format RECORD` we'll still need `--format TEXT` to describe things like `globus ls`, `globus bookmark locate`, `globus task wait`, and `globus whoami` output.

I don't see what we gain by shoehorning non-tabular data into a table or tabular data into colon-delimited output.


The nice thing about `--format TEXT` and `--format JSON` is that _every single command_ should support them. In some cases, this is a cop-out because the text output is just JSON, but that's something we're working to improve. There are a few misses (`task wait` and `whoami` don't support `JSON`, which I'm about to file a bug about), but the intent is that these formats are global, so that you don't have to check what formats a command supports before requesting output.

**Comment by tuecke** [comment]
> Yes, tabular data is produced as a table, and single records are colon-delimited.
> 
> I don't see this behavior as inconsistent, and think that adding more formatting options only serves to confuse things and make more work for us.

I hate it, for 2 reasons:

1. I find the two different output formats jarring.  I understand there is a logic to it, but it just seems really inconsistent to me.
2. I generally don't like the ascii-art table format output, because for many commands, unless I have my terminal window set very wide, it does weird wrapping.   

I'd at least like to be able to get the record-based output, rather than being forced to deal with ascii-art tables that are impossible to parse if they line wrap.  My only alternative is to switch to JSON format, which I found myself doing from time to time, but its not the most human-friendly.

We need to add --format=csv and csvh anyway.  So I'm assuming we'll have some sort of pluggable output formatter.  So I'm just asking that we also do a record based output formatter.

I don't feel super-strongly about having the default output always be one or the other -- if others like a default that some commands are tables, and some are records, I'm ok with that.

> If we have --format TABLE and --format RECORD we'll still need --format TEXT to describe things like globus ls, globus bookmark locate, globus task wait, and globus whoami output.

Commands that outputting a singular output value shouldn't be allowing --forward XXX options at all.

**Comment by sirosen** [comment]
> Commands that outputting a singular output value shouldn't be allowing --format XXX options at all.

They definitely need to support `--format JSON` -- that's how we provide a uniform machine-parseable format. And once they support `--format JSON`, then you need a descriptor for non-JSON output so that you can append a respecification of format to a prior command.

I feel very strongly about all commands which are at all capable supporting JSON output. We may want exceptions in rare cases like `globus login`, as streaming JSON output is messy.

> I generally don't like the ascii-art table format output, because for many commands, unless I have my terminal window set very wide, it does weird wrapping.

I totally get this. I don't really love the wide format of the tables either, and they're terrible when they line wrap. I did consider having a hard wrap at 80 characters, as it's much friendlier to small terminals, but solving the problem of how to present tabular data at a fixed width was not on the docket early in development.

If we're talking about supporting "record-oriented" output for tabular data, that makes sense as a possible solution to this problem.

> I find the two different output formats jarring. I understand there is a logic to it, but it just seems really inconsistent to me.
> ...
> I don't feel super-strongly about having the default output always be one or the other -- if others like a default that some commands are tables, and some are records, I'm ok with that.

At first glance, these feel like they're in conflict with one another.
It's sounding to me like you're comfortable with the current outputs (excepting the open issues to the contrary), but are feeling hampered by the fact that tabular data is _always_ in the ASCII-art table.
Is that an accurate, if brief, summary?

---

As soon as we provide a formatting option like `--format RECORD`, we're implying a stable and parseable output format.
That's not all bad, as I'd rather have a textual parseable format which we actually support than letting people try to parse arbitrary text and have it work "most of the time" with no promise of support.

I'm not sure it makes sense to coerce non-tabular data into the table format, however.
If we add a CSV format, being able to get individual bits of data as CSV rows is presumably desirable, and similar enough.

**Comment by sirosen** [comment]
#144 is closed, so closing this as well.
