### ISSUE TITLE
bookmark locate: Fold this into bookmark show

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#182]
Instead of a separate "bookmark locate" command, why not just fold this into "bookmark show" as an option.  Perhaps use "-l" or "--location" as the option name.

For example:

$ globus bookmark show 'foo bar' -l
af7bda53-6d04-11e5-ba46-22000b92c6ec:/~/myproject/

I don't feel strongly about this change, but the current approach just feels overly redundant to me.

**Comment by sirosen** [comment]
> the current approach just feels overly redundant to me.

Agree. IIRC, we did it this way because the actual implementation is quite different from `bookmark show`.
I think `--location` is okay, but maybe we can get something better on the table. `globus bookmark show --path "foo"`?

cc @corpulentcoffee, as he was the one to think of `bookmark locate` in the first place.

**Comment by corpulentcoffee** [comment]
We decided on `globus bookmark locate` only because one of the common usages was command substitution, and something like `globus ls --long $(globus bookmark locate "Foo Bar")` was (marginally) less noisy than something like `globus ls --long $(globus bookmark show --locate "Foo Bar")`.

**Comment by aaschaer** [comment]
Redundant with #225 which was closed by #236
