### ISSUE TITLE
endpoint_id:path vs. endpoint_id/path

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#191]
In the ssh CLI we deprecated the SCP-like : separator between endpoint_id and path.  So this is deprecated:
af7bda53-6d04-11e5-ba46-22000b92c6ec:/~/myproject

Instead it should be a URL-like separator of /, such as:
af7bda53-6d04-11e5-ba46-22000b92c6ec/~/myproject

This URL-like separator is also more consistent with where endpoints are going with HTTPS, as every endpoint will have a DNS name, with URL path naming.  We should adopt this same style consistently throughout the new CLI.

**Comment by sirosen** [comment]
@corpulentcoffee might recall better than I do, but I think we went to the colon-based notation because otherwise there is no way to disambiguate a relative path from an absolute path.

i.e. `ENDPOINT_ID/abc` indicates the dir `/abc` and it's not possible in that case to refer to the relative path `abc`.

`/~/` turns into a problem on S3 endpoints, where `/~/` isn't supported, which I think is why we were not satisfied with the `ENDPOINT_ID/~/abc` hack.

Also, it's very sloppy looking and is inferior for cases in which someone wants to produce an endpoint ID and a path from some set of commands and feed them to us.

If I have
```shell
ep_id="$(somecmd1)"
path="$(somecmd2)"
```
then it's very easy today to pass the CLI `"${ep_id}:${path}"`.
If the separator is slash, which is also a component character in the path, and we require `/~/` for relative paths, then CLI users need to do an extra round of
```shell
if [ "$(echo "$path" | grep '^/')" == "$path" ];
then
    path='/~/'"$path"
fi
```

It's error prone extra work we're foisting onto CLI consumers.

> This URL-like separator is also more consistent with where endpoints are going with HTTPS, as every endpoint will have a DNS name, with URL path naming.

I understand the desire for non-HTTPS endpoints to be "on the same page" as HTTPS ones, but they'll always be inconsistent.
HTTPS endpoints have no meaningful use for `/~/`, they have a scheme associated with them, their paths must be url-safe, and they are identified primarily via DNS rather than a UUID.
Shared endpoints won't have DNS names in most cases, and likely many existing endpoints will never bother to set them up even when we support it.

Allowing `[UUID or Hostname]:[path]` as a valid "endpoint plus path" notation seems as consistent as any other approach, even if we also accept `https://[Hostname]/[path]`.

**Comment by corpulentcoffee** [comment]
Yes, the relative path case was exactly why.

We had one proposal that made the colon optional for endpoint+path arguments that were absolute, but I think we didn't do that just because of the added complexity.

**Comment by ranantha** [comment]
Discussed with Steve, we agreed to keep the endpoint_id:path format. Please close this issue.
