### ISSUE TITLE
Respect output format for error presentation whenever possible

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#20]
@bd4 I want us to discuss this a little bit.

I think it makes a lot of sense that `globus transfer ls --format json --endpoint-id 'badepid'` would produce a JSON error message.

However, there are a number of conditions under which we do not receive JSON from the other end of the connection.
For example, the web server may respond with a raw body of `500 Internal Server Error`.
In those cases, should we wrap this in a standard JSON container, like `{"message": "500 Internal Server Error"}` ?

To me, the target use case is stuff like nonexistent endpoints, which the caller may want to parse and inspect.
They should be able to, _relatively_ safely, hand stderr to something that consumes JSON.

I think that would be totally acceptable, but I'm not sure I've thought through all of the options.
There are errors that we can't handle so easily in this way, namely Python stacktraces.
I don't want to be JSONifying every exception ever thrown, just to slavishly obey the request for `--format JSON`

Where do we draw the line? Do we say "We will convert any error responses from the APIs to JSON." ?
If we can't crystalize this into a simple statement, we probably don't have clear enough thinking about it yet.

**Comment by bd4** [comment]
The Transfer API almost always returns JSON error messages, even for most 500 errors (if caused by internal python exception and not by Apache config). Other APIs may not be as uniform - I like the idea of guaranteeing that the error is JSONified if we get plaintext from the server, with maybe a size limit on the message length.

Not guaranteeing JSON in the case of uncaught python code errors in SDK/CLI seems reasonable to me - hiding them in a log file may just make it harder to get good github issues and support requests. The most important thing functionally for users is the nonzero exit code.

**Comment by sirosen** [comment]
I've started doing this for all errors that originate within the SDK. That is, if it's a flavor of `globus_sdk.exc.GlobusError`, we'll handle it as JSON.

`GLOBUS_CLI_DEBUGMODE` short-circuits past the relevant logic, in case we ever need a full stacktrace.

Right now the generic handler is based on `str(exception)`, which just requires that we're careful to present good string versions of the exception. This has maybe-undesirable behavior with SDK network errors, as we get requests-related info in the output, rather than something more digestible like "NetworkError: Couldn't reach https://transfer.api.globus.org/..."

@bd4 I'm pretty comfortable with closing this with the new behavior.
Do you feel strongly that we need to pretty-up the handling of `globus_sdk.exc.NetworkError` and its subclasses?

**Comment by sirosen** [comment]
Discussed face-to-face. Agreed that special handling of `NetworkError` can come later.
