### ISSUE TITLE
Symlink Support

### ISSUE THREAD

**Issue by aaschaer** [globus/globus-cli#321]
Here is my proposal for how we should add Transfer's upcoming support of symlinks to the CLI:

**Task Submission** 

Add a `--recursive-symlinks [keep | copy | ignore]` option to `globus transfer` that gets passed through the SDK as the `recursive_symlinks` query parameter for Transfer.

Add a `--symlink` option to `globus transfer` with usage similar to `--recursive` on both single item and batch transfers to mark that a `transfer_symlink_item` should be used instead of a `transfer_item` to transfer a symlink rather than the target of a symlink. If both `--symlink` and `--recursive` are given for an item, the CLI should throw a usage error.

**Task Monitoring:**

Add `Symlinks` and `Recursive Symlinks` to the `TRANSFER_FIELDS` for output used by `globus task show`
that will display the new `symlinks` and `recursive_symlinks` fields in the task document.

**Directory Listing:**

For `--long` output of `globus ls`, change the behavior of the File Type and Filename output fields to also look at the `link_target` response field. If `link_target` is not None, display "`name` -> `link_target`" as the Filename, and append " (symlink)" to `type` for File Type output if the `type` is not `invalid_symlink`.

e.g. a valid symlink pointing to a file at /tmp/file.txt would have a File Type of `file (symlink)` and a Filename of `test.txt -> /tmp/file.txt`.

For `--recursive` usage of `globus ls` add a `--follow-symlinks` flag that will also follow valid symlinks to directories while making recursive calls to `operation_ls`. We may want to deal with #46 before we do this.

**Symlink Creation**

Add a `globus symlink` command with usage `globus symlink [OPTIONS] ENDPOINT_ID TARGET_PATH LINK_PATH`
that just passes `ENDPOINT_ID`, `TARGET_PATH`, and `LINK_PATH` to the SDK's new `TransferClient.operation_symlink` method.

**Comment by aaschaer** [comment]
Updated to add Directory Listing, coloring might be a bit much, especially since defaults vary and legibility is an issue, but I added it for now as it could be helpful.

**Comment by sirosen** [comment]
A note on colorized output, if we decide to use it at all:
`ls` detects whether or not it is writing to a terminal before colorizing its output, so that it doesn't blurt out ANSI color codes when used in a pipeline. I think we would need to use the same behavior, or people will likely be surprised (read: dismayed) by the results.

We could also use `LS_COLORS` to determine correct colorization, but it's a bit of a pain to parse.

---

I think we can decide to strictly not follow symlinks when doing a recursive `ls`. The GNU `ls` tool doesn't support it -- why should we, right?
That is, `ls -R some_link/` works, but it doesn't follow any dir symlinks it encounters.

That aside, I agree that we want to deal with #46 and the potential SDK support for recursive `ls` before doing anything here.

---

`globus symlink [OPTIONS] ENDPOINT_ID:SOURCE_PATH TARGET_PATH` makes me a little bit nervous, as it's odd to require the endpoint with only one of the two paths. I'm not sure that there's a phrasing of it that isn't confusing, but a couple of notes:

- It's probably worth following the convention set by `ln` and providing the link target, followed by the link path. Personally, I always find this ordering counterintuitive, but I think it would be _more_ confusing to do the opposite, since everyone knows `ln`
- It may be better to not use the `ENDPOINT:PATH` notation at all for this, and make `ENDPOINT TARGET LINK_PATH` the args
- We _could_ add a version of `EndpointPlusPath` params where the endpoint is optional, behaving the same way as the optpath version does, and require that we get at least one endpoint and that if there are 2 endpoints, they must match. I'm not sure that this would be a good idea

**Comment by JasonAlt** [comment]
No coloring for this release; if we were to add coloring it would need to be applied to the entire CLI not just listings.

**Comment by sirosen** [comment]
> if we were to add coloring it would need to be applied to the entire CLI not just listings

Why? We have a use-case that gives it utility in `ls`.

Not that I'm particularly much in favor of adding colors, personally -- I think it's probably unnecessary in general -- but I'm not even aware of another place in the CLI where colored output makes particular sense.

**Comment by aaschaer** [comment]
Removed coloring from proposal and changed arguments to `globus symlink` to be consistent with ln as suggested. I think having `ENDPOINT_ID` be its own argument is probably the least confusing option for passing one endpoint and two paths on the same endpoint.

Also, I considered naming the symlink creation command `globus ln`, but I'm guessing that would confuse people as `ln` defaults to hard links?

**Comment by sirosen** [comment]
> Also, I considered naming the symlink creation command `globus ln`, but I'm guessing that would confuse people as `ln` defaults to hard links?

Yeah. Imagine how this would evolve if we got feature requests for hardlink support -- `ln` would mean symlinks, and `ln --someflag` would mean hardlinks? Yuck.

**Comment by aaschaer** [comment]
After testing a bit against sandbox a few questions/changes cropped up:

1. `globus ls --recursive` as it is implemented now will follow valid symlinks (since their `type` is still `dir`), I'm thinking we want that not to be the default, but add a `--follow-symlinks` option instead. (Should we explicitly prevent cycles, or just let the depth cap prevent infinite dir expansion?)

2. `globus rename` uses two ENDPOINT_ID:PATH arguments and just requires that both endpoint_ids are for the same endpoint. I think `globus symlink` should do the same for consistency? (although I would prefer only passing the endpoint_id once otherwise)

**Comment by ranantha** [comment]
@aaschaer can you write up the reference document on these options so I can see what the user will see? My first instinct here is to look for similar options I see when I use the webapp, that allows user to pick what needs to happen in first tier, and recursively. And that is not apparent reading the text here.

**Comment by sirosen** [comment]
RE: following symlinks

`ls` decides on this behavior based on `-L`. But `-L` controls more than just listing expansion; it also switches between seeing symlink stat info vs. real file info (toy dir I created):
```shell
# with `-L`
$ ls -RLl a
a:
total 8
drwxr-xr-x 3 sirosen sirosen 4096 Aug 15 13:57 b
drwxr-xr-x 3 sirosen sirosen 4096 Aug 15 13:57 d

a/b:
total 4
drwxr-xr-x 2 sirosen sirosen 4096 Aug 15 13:57 c

a/b/c:
total 0

a/d:
total 4
drwxr-xr-x 2 sirosen sirosen 4096 Aug 15 13:57 c

a/d/c:
total 0

# without `-L`
$ ls -Rl a
a:
total 4
drwxr-xr-x 3 sirosen sirosen 4096 Aug 15 13:57 b
lrwxrwxrwx 1 sirosen sirosen    1 Aug 15 13:57 d -> b

a/b:
total 4
drwxr-xr-x 2 sirosen sirosen 4096 Aug 15 13:57 c

a/b/c:
total 0
```

That means you can't ask `ls` to follow links as it recurses, but still give true stat info. I've ever needed that, but it seems wrong.

👍 for `--follow-symlinks` as a name -- and I think the behavior should be explicit -- but rather than doing what `ls` does, I like always showing links as links. We can add a future `--dereference-symlinks` option for those who want symlinks to appear as their targets in long-form listings.

---

RE: `globus rename`

Regarding `globus rename`, I agree that we're inconsistent, but have no strong opinion as to which is superior. We should disucss/decide which is best, and apply that decision to all multi-file+single-endpoint ops.

**Comment by aaschaer** [comment]
@ranantha here are excerpts from the options sections of the adoc reference pages I am editing along side these changes. I hope this is what you are asking for?

-----

from `globus transfer`:

*--recursive-symlinks [keep|copy|ignore]*::

During recursive transfers, either `keep` source symlinks as symlinks on the
destination, `copy` the target of source symlinks to the destination, or 
`ignore` any symlinks on the source.

*--symlink*:: 

Transfer the symlink at SOURCE_PATH as a symlink, rather than as the target the
symlink at SOURCE_PATH links to. Mutually exclusive with --recursive.

-----

from `globus ls`:

*-l, --long*::

Long form tabular output similar to 'ls -l'.

*--follow-symlinks*::

During recursive listings follow symlinks to directories and continue
the recursive listing within the linked directory. If links form a cycle
the cycle will be followed until the recursive-depth-limit is reached.

-----

@sirosen I prefer ENDPOINT_ID SOURCE_PATH DEST_PATH over ENDPOINT_ID:SOURCE_PATH ENDPOINT_ID:DEST_PATH for multi path single endpoint arguments, but don't know if changing `globus rename` in such a non-backwards compatible way is worth having cleaner arguments?

**Comment by ranantha** [comment]
@aaschaer as discussed yesterday, please add a couple of examples for "copy first tier and keep rest" and "keep all" options. Some text edits below. 

--recursive-symlinks [keep|copy|ignore]::

Choose how transfer task will handle symlinks on source endpoint during recursive transfers.

keep will create symlinks on the destination
copy will copy all data symlinks point to to the destination endpoint
ignore will skip all symlinks 

--symlink::

Keep the symlink at SOURCE_PATH as a symlink, and create it on the destination endpoint. Mutually exclusive with --recursive.

**Comment by vanderwb** [comment]
It appears that the last action on this issue occurred almost a year ago. Is there still any momentum for adding symlink support to Globus? We have users that would like to use Globus to transfer their work across our file systems, but the lack of symlink handling is prohibitive in many cases.

**Comment by ranantha** [comment]
This effort was paused, and we plan to add support for symlink handling in version 5 of Globus Connect Server. That version is being actively worked on now, and we expect sometime early next year to be able to add such support.
