### ISSUE TITLE
How to login via CLI with no Web browser intervention?

### ISSUE THREAD

**Issue by achourasia** [globus/globus-cli#330]
I have a use case where a CLI script needs to create an endpoint and share it with someone.
Is it possible to login via CLI without needing to visit the web browser? If not, what is an alternative?

**Comment by jaswilli** [comment]
Hi @achourasia,

In order to establish a session with the CLI you have to go through the browser login flow at least once. After that it should continue to work with no human intervention as long as a command is run at least once every 6 months (the underlying refresh tokens will expire if not used once every 6 months).

If you absolutely cannot go through the browser login flow, you might want to consider using our SDK (Python), which can be found at https://github.com/globus/globus-sdk-python. You would be able to use something called the [client credentials grant](http://globus-sdk-python.readthedocs.io/en/stable/examples/client_credentials/) which is a way for an application to authenticate "as itself" for situations where it doesn't work to require a human to log in.

**Comment by achourasia** [comment]
The CLI could work if its a one time setup. Which specific command needs to be issued for refreshing underlying token?

For example could anything like this work
> globus endpoint search --filter-scope shared-by-me

Or the manual drill using the web browser needs to be done again in six months?

Thanks for very swift response.

**Comment by jaswilli** [comment]
> The CLI could work if its a one time setup. Which specific command needs to be issued for refreshing underlying token?

Yes, it's just a one time thing to get logged in. You don't need to do anything special to get a refresh token (that's the default behavior).

> Or the manual drill using the web browser needs to be done again in six months?

No, as long as you use the CLI at least once every 6 months it will stay logged in indefinitely.

**Comment by achourasia** [comment]
Perfect, I'll go CLI route for the time being.
Thanks

**Comment by jaswilli** [comment]
Great! Let us know if you have any more questions.
