### ISSUE TITLE
Make `endpoint server create` take hostname as positional argument, not required option

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#390]
@corpulentcoffee, I'm asking you to help look at this since you're reviewing #389 already.

Right now, `endpoint server create` takes a required option, `--hostname`.
e.g. `globus endpoint server create $epid --hostname foo.com`

We've gotten rid of basically all of our required options, but this one lingers.
I think we can change the command to better line up with `endpoint server delete $epid foo.com` by doing this:
- `--hostname` is an option which takes no values and does nothing
- usage becomes `globus endpoint server create ENDPOINT HOSTNAME`

Does this look right to you? Any current, correct usage of the command should continue to work fine, as we're replacing a required option with a positional arg, but stopping the option (now optional) from consuming a value.

`--hostname` would be marked deprecated and slated for removal in CLI v2

That's my reasoning, but I wanted to think about it/potentially discuss before even proposing the change in a PR.

**Comment by corpulentcoffee** [comment]
I haven't tried it, but I *think* that how you have proposed it would be backward-incompatible for a caller using the option with an equal sign, e.g. <code>globus endpoint server add $epid --hostname<strong>=</strong>example.com</code>, which wouldn't be uncommon usage.

It might also be backward-incompatible with `globus endpoint server add --hostname example.com  $epid`, although that is a more contrived usage.

It also wouldn't get us *fully*-lined-up with `globus endpoint server delete` anyway since that command be used without the `--port` and `--scheme` flags that `globus endpoint server add` currently requires.

**Comment by sirosen** [comment]
I forgot about `--hostname=foo.com`. I don't think putting the option before the endpoint ID is a big worry, but I'd not like to be wrong.

Between these things (and the fact that it won't be, as you say, 100% uniform), maybe I should just slate this for v2? I'd like to make it at some point -- the result seems a bit cleaner.

**Comment by corpulentcoffee** [comment]
I think tagging this as `breaking-change-requires-v2` would be fine.
