### ISSUE TITLE
Python 3 support for Globus Connect Personal Linux

### ISSUE THREAD

**Issue by vsoch** [globus/globus-cli#405]
Hey maintainers! The globuspersonaconnect (no Github repo) seems to still be in Python 2:

```python
Generating Globus Personal Endpoint
  File "/opt/globus/gc-ctrl.py", line 29
    print GCP_VERSION
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int GCP_VERSION)?
```
And I am going to have to install an entire python 2 in the container just to support this. Could you please  make a repo for this somewhere? I'd be happy to PR with changes for Python 3. Thanks!

**Comment by sirosen** [comment]
I think it's much wiser to install python2 in whatever environment is running Globus Connect Personal.
That code is written to function using only standard library python 2.6 or 2.7, and has to function on a wide range of platforms. It has to support the oldest supported RHEL variants, at the very least.

Keeping code compatible with python 2.6, 2.7, 3.4, 3.5, 3.6, 3.7 is non-trivial, and I'm not sure we want to commit to maintaining such a codebase.

I'm asking the maintainers if they'd be interested in accepting and supporting a patch for compatibility with all of the above pythons. However, I wouldn't be surprised if they'd rather wait for the RHEL 6 EOL in 2020 so that they can drop support for python2.6 and do a cleaner rewrite.

**Comment by vsoch** [comment]
It's really a burden to have to install an entire system python just for what comes down to some extra parentheses, especially for one tiny script. Looking closer, it's mostly just printing. If you aren't going to support this then my preference will be to fix it for my application and save the extra space and huge potential for conflicts with having more than one python!

**Comment by sirosen** [comment]
So, I was just chatting with one of the Globus Connect Personal maintainers, and they're open to a fix for this (which surprises me, but in a good way).

However, the Globus Connect Personal project is closed source, and we don't have a clear-cut policy for licensing, ownership, and contributions. We're aware that it's super-weird to call a python project, where you can see and read the source, "closed source", and we're trying to figure out the right way to accept contributions. I'm starting some conversations with several people and hopefully I can get back to you with some reasonable answer shortly.

**Comment by vsoch** [comment]
Woohoo awesome!! :D

**Comment by sirosen** [comment]
While waiting for some details on the legal/licensing situation, I submitted a patch for review which makes the code python3 compatible. [I threw it into a temporary repo](https://github.com/sirosen/globusconnectpersonal-py3-patched) so that you can pull it down, apply it, and see if it works for you. Nobody else has reviewed it yet, so caveat emptor!

If you want to make changes and submit them to us, the word I've gotten is that we need written confirmation from you that you are submitting changes to us under our (brand new) Community License for Globus Connect Personal/Server: https://www.globus.org/legal/source-license

I think the easiest way to handle this would be to send us patch files in an email (support@globus.org or directly to me sirosen@globus.org) with a statement that the patches are sent under that license.
Not as clean as a PR, but I don't have time to burn on trying to rearrange things.

---

I'll leave this issue open until either the patch is merged and released or rejected.
However, in the future, I think it would be best if you submitted issues about Globus Connect Personal to support@globus.org or asked on developer-discuss@globus.org

That will put you in more direct contact with the maintainers of that project, and not with the SDK and CLI developers. We are clients and consumers of Globus Connect Personal, just as you are, and really not the best people to be fielding questions about that software.
I don't mind being a middleman when it's not clear where an issue should be filed or the distinction between components is unclear, but it's definitely less efficient than a direct conversation.

**Comment by sirosen** [comment]
Reviewing old issues, I found that the python3-compatibility change to Globus Connect Personal was merged a little bit ago and is present in recent releases. Closing as resolved.

**Comment by vsoch** [comment]
Hooray! And you have three months to spare! https://pythonclock.org/
