### ISSUE TITLE
Keep track of "logged-in" Identity

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#44]
Provide a way for a user to see what identity-context they're operating under. Something like `globus whoami` that shows the primary/effective identity that the current set of tokens was issued to.

See also #38 for more "CLI session lifecycle" material.

**Comment by sirosen** [comment]
I think we get back an `id_token` with the `globus login` flow.
We could install `python-jose` to get the parsing capabilities and store either the raw token or the parsed result alongside the refresh tokens.

Like refresh tokens, I think this really needs the "environment prefixing" hackery even though it's just cosmetic -- otherwise it's likely to confuse people.


`globus whoami` is cool because we can advertise a `PS1` customization to show your globus identity username.
That use case suggests that we should store parsed results (and not have people making a call every time their prompt refreshes).

**Comment by jaswilli** [comment]
> We could install python-jose to get the parsing capabilities and store either the raw token or the parsed result alongside the refresh tokens.

I think that's going to impact Windows users as it looks like getting `pycrypto` installed is manual process on Windows in most cases.

**Comment by sirosen** [comment]
I'm okay with (for the foreseeable future) providing a degraded experience to Windows users.
Can we use setuptools' platform detection to skip that dependency on Windows, and only provide this feature if `python-jose` is installed? (SDK makes this a try-catch with `OptionalDependencyError`).
