### ISSUE TITLE
Map custom exit code to task wait timeout

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#450]
Some context: https://github.com/globus/automation-examples/issues/5
Original issue where this feature came in: https://github.com/globus/globus-cli/issues/59

I think we can leave all the current default behavior in place, i.e., if the timeout period is exceeded the CLI exits with code `1`.

We can add a new option to the `task wait` command, e.g., `--timeout-exit-code <integer>` so the exit status can be mapped to whatever the user desires (including `0`).

**Comment by sirosen** [comment]
Why not just switch to "timeout exceeded -> exit(3)"? That seems simpler and less work (both for us and for most consumers) than a new option.

Nothing mandates that we stick to `exit(1)` for all failures.
`exit(2)` is taken up for argument handling, but we have statuses 3-50 available for use before you run into [the range used by `--map-http-status`](https://github.com/globus/globus-cli/blob/bc5696e6af0d17ad7b811ab0afdae347f4116752/globus_cli/parsing/command_state.py#L176-L180).

This change would theoretically break anyone checking if `$? -eq 1`, but it wouldn't break anyone looking at `$? -ne 0`, which I think is way more likely anyway. Especially in a `task-wait` polling loop.

**Comment by rpwagner** [comment]
A user specifically asked for `0` for whenever the transfer is still processing, even if the timeout is exceeded. I can ask them if `3` would work. (This gets embedded into a workflow script that uses return codes heavily.)

**Comment by rpwagner** [comment]
But just adding the mapping code would fit their use case.

**Comment by sirosen** [comment]
> A user specifically asked for `0` for whenever the transfer is still processing, even if the timeout is exceeded. I can ask them if `3` would work.

I can tell you right now that status 3 definitely works for this use case.

You could even write the tiny wrapper,
```shell
#!/bin/bash
# my-task-wait.sh
set +e
globus task wait "$1"
rc=$?
case "$rc" in
  "3")
     exit 3
     ;;
   *)
     exit "$rc"
     ;;
esac
```

The issue isn't, therefore, "whether or not it works" but "what provides the best experience for _all_ CLI users". I'm not clear that tacking on extra options left and right -- when the shell is an environment capable of handling meaningful status codes already -- is better than documenting that a command has a special status code which you may, as a consumer, want to handle differently.

A single user's narrow view of the problem will usually be that their specific use-case should be addressed _directly_, but addressing it _indirectly_ may actually lead to a more coherent product.

**Comment by sirosen** [comment]
I should clarify my position on this:

If I were building this from scratch without any backwards compat concern, I'd make `exit(3)` the timeout behavior and challenge anyone to move me off of that because it's simple.

How worried are we that someone is checking `-eq 1` vs `-ne 0`? Is that change scary?
If it is, or we're even a bit concerned that documenting `exit(3)` isn't better than documenting a new option, then let's just add `--timeout-exit-status` with the `0,1,50-99` range available.

I don't want a single user's desire for `exit(0)` behavior to drive us to choose the worse option.

**Comment by sirosen** [comment]
I discussed very briefly with Jason, and quickly convinced myself that I'm making a problem which doesn't need to be made.
Adding a single option specific to that command is not a big deal. We should just do it and not worry more about it. It saves us all effort/cycles to have something implemented and done, rather than debating the merits of one choice over the other, given that there are tradeoffs.
