### ISSUE TITLE
globus transfer --batch: accept list with single column

### ISSUE THREAD

**Issue by rpwagner** [globus/globus-cli#478]
When submitting transfers using batch, if the input file only has a single column of files, assume that the source and destination files should have the same name or relative paths to `SOURCE_ENDPOINT_ID[:SOURCE_PATH]` and `DEST_ENDPOINT_ID[:DEST_PATH]`. Currently, the file has to have a set of identical columns, unless I've missed something in the call.

**Comment by sirosen** [comment]
I'm trying to determine the desirability of this feature. I'm inclined to close it unless you have some use-case which strongly drives a need for it.

Here are my reasons:
- optional positional parameters are generally poor UX for CLI apps
- `... | awk '{print $1 " " $1}'` is a very small inclusion for a pipeline (and there many equivalents, e.g. `sed 's/\(.* \)\(.*$\)/\1\1\2/'`)
- parsing ambiguity arises as to whether or not an optional command-line `SOURCE_PATH` should be included as part of the `DEST_PATH`

Is there more context (e.g. a common pipeline where this usage arises naturally), or is this just a noted "nice to have"?

I understand that supporting this is desirable for your specific case, but I'm not convinced that it's desirable as a general-case feature -- especially weighed against a single awk, perl, sed, etc. expression added to a workflow.

**Comment by rpwagner** [comment]
I think this is the more common pattern that users expect, based on their experience using tools like `scp` which does recursive transfers. This is due to scientific datasets having fixed file hierarchies that need to be preserved, so once you pick your source files, you want the same structure on the destination. I would not suggest this for the API or SDK, but as a means to match the typical usage patterns.

Note that this doesn't break existing functionality, it just saves a step.  While all the tools you mention are valid solutions, a researcher on the command line may not be skilled with them and potentially hand editing files to generate columns. When I [wrote up an example](https://github.com/globus/automation-examples/blob/master/batch.md) of doing a batch transfer I kept it as simple as possible to make it approachable.

**Comment by sirosen** [comment]
I don't follow the point about `scp` -- we support recursive directory transfers as well. In fact, that's one of the reasons that I don't understand when and why this feature comes up as desirable. We support it inside of cli batch mode and with non-batch invocation.

When do you need to sync a specific set of files and directories between two endpoints
- with the same directory structure
- not a recursive dir sync
- potentially multiple unrelated root dirs
- must be a single task
- recursive parent dir creation is *not* wanted
?

I understand wanting related features which we can't do client-side, e.g. exclude globs. But this functionality -- syncing specific files between two dirs -- is something that neither rsync nor scp handle particularly gracefully in my experience.

What is the use case that we have for this, specifically? Can you point me at an example which explains it? Without clarity on this, the case against this feature -- parsing ambiguity, poor UX -- remains strong.

**Comment by rpwagner** [comment]
Good point about `scp` for recursive transfers for single directories, that's pretty equivalent.

I linked to [this use case](https://github.com/globus/automation-examples/blob/master/batch.md) in my previous comment. It boils to generating a list of files on one endpoint, and having them transferred to a base directory on another endpoint. What I did was all through the CLI for listing and then transferring the files, but it would also apply if I was working on the local files system.

As an example, a user could have a current working directory with a bunch of files that they want to transfer, and a bunch they don't (temp files, not relevant, whatever). Once they build the list of files via `find`, or `ls` and `grep`, they just want that entire tree to appear on another endpoint as-is. This gets submitted with a bunch of files listed with full paths, but the user's mental model "take these files from this directory and put them over there".

I think this is much more common than the alternative, where they have a list of files, and they want them on another endpoint in different locations or renamed. I know that does happen, because we've done it for some cases, just less often.

**Comment by sirosen** [comment]
> I linked to [this use case](https://github.com/globus/automation-examples/blob/master/batch.md) in my previous comment. It boils to generating a list of files on one endpoint, and having them transferred to a base directory on another endpoint. What I did was all through the CLI for listing and then transferring the files, but it would also apply if I was working on the local files system.

Ah, I think we're disagreeing about what constitutes a use-case. This is an _internal_ document, in which we're showing how to do things. That's not the same as _external_ user demand.

To make the absurdist argument: if I write a script for the CLI documentation which does recursive exclude glob expansion over a directory tree and submits the result to Transfer, I (obviously) can't use that to argue that the CLI should support that behavior.

You're not going that far, but what I'm looking for in use-cases is really "how much is it hurting users today to not have this"? Because I need to weigh that against "how much will it hurt the CLI's maintainability" and "how much will it hurt other users who are confused by this behavior"?

I'm not convinced that our own examples repo is the right place to start for such a question.
I also grant, vis-a-vis the CLI, _you_ are a user, being a member of Globus is immaterial. But are you the only user thus impacted?

> As an example, a user could have a current working directory with a bunch of files that they want to transfer, and a bunch they don't (temp files, not relevant, whatever). Once they build the list of files via `find`, or `ls` and `grep`, they just want that entire tree to appear on another endpoint as-is. This gets submitted with a bunch of files listed with full paths, but the user's mental model "take these files from this directory and put them over there".

This is a good scenario, but if the user is building a file-listing with `find`, are they not the same class of user who will not struggle with `awk '{print $1 " " $1}'`?
And if we want to document that as a way to use the CLI, is that documentation not satisfactory for these users, such that they need a built-in solution?

Could we not just as well tell users who want such behavior to
```shell
mkdir ~/syncdir
for x in $files; do mv $x ~/syncdir/; done
globus transfer --recursive \
  "$(globus endpoint local-id):/~/syncdir" \
  "$(globus bookmark show "my bookmark name")"
```
?

> I think this is much more common than the alternative, where they have a list of files, and they want them on another endpoint in different locations or renamed. I know that does happen, because we've done it for some cases, just less often.

This isn't the usage that I'm comparing against, however. I'm really comparing against a recursive directory transfer of the desired directory.

That is, `globus transfer --recursive "$(globus endpoint local-id):/foodir" "$ep2:/bardir"`, including all of the cruft and tempfiles and so forth.
Why would our users not be satisfied with our tools providing basically the same interface as `scp`?

---

We can implement this just fine. The trouble is that I'm _still_ not convinced there are enough users who want this for it to be worth doing (i.e. the value vs maintenance burden tradeoff).

We can actually implement this multiple different ways because anytime a tool "implicitly copies" an input, it makes assumptions -- this leads to usage ambiguities. You probably have in your head some clear idea of how this would/should behave, e.g. that it should verbatim copy a column of input as a string. However, that kind of naive approach will fall over in all sorts of cases.

Just to give an example, consider a source-path which is absolute + a command-line dest path: the dest path is ignored if you copy the source-path verbatim. Is that correct? I don't even know. I'd rather not be making those kinds of guesses. Forcing users to be explicit about what they want means we don't risk violating their expectations. That's not to be underestimated in value.

Absent a preponderance of evidence that this is really a good idea, and with a known way to achieve desired results without the feature + the knowledge that we're highly resource constrained in what we can devote to globus-cli development, I'm closing this.

You can email me if you want to discuss further, but I think this is a feature which appears good and easy only from the perspective of a user with the precise use-case that it solves. From the perspective of the maintainer, who has to worry about _all of the users_ and their experience with the tool, as well as the tool's upkeep, I can't get onboard with this.
