### ISSUE TITLE
Existing Globus Identities not Found

### ISSUE THREAD

**Issue by rpwagner** [globus/globus-cli#501]
When calling `globus get-identities`, identities that are found in the web app aren't showing up. For example, when looking for a coworkers identity as a test case

```
$ globus update
You are already running the latest version: 1.14.0
$ globus whoami
rpwagner@globusid.org
$ globus get-identities amoxley@ucsd.edu
NO_SUCH_IDENTITY
$ globus get-identities -v amoxley@ucsd.edu
ID | Username | Full Name | Organization | Email Address
-- | -------- | --------- | ------------ | -------------
```

However, when searching via the web app, I see
<img width="956" alt="Screen Shot 2020-11-24 at 1 12 59 PM" src="https://user-images.githubusercontent.com/163203/100152677-e8574d00-2e57-11eb-8f67-779de259026f.png">.

Does the CLI not have the same ability to search across email addresses? 

I'm actually not sure why this works for one of my identities, since UCDS uses opaque usernames for the subject.
```
$ globus get-identities -v rpwagner@ucsd.edu
ID                                   | Username          | Full Name | Organization | Email Address    
------------------------------------ | ----------------- | --------- | ------------ | -----------------
e28bb1b1-b5fb-411d-8378-b83f53a6bff7 | rpwagner@ucsd.edu | NULL      | NULL         | rpwagner@ucsd.edu
```

**Comment by sirosen** [comment]
Because there is no way to search users in the public APIs, there's nothing we can do in the CLI to resolve this at present.
The webapp uses a private API for user search. (Aside: I strongly encourage you to email outreach@globus.org or support@globus.org and link this ticket to request this feature.)

So with respect to

> Does the CLI not have the same ability to search across email addresses?

The answer is unfortunately "no".

It is possible that `rpwagner@ucsd.edu` has been grandfathered in to have that username, or is otherwise being treated specially. It's also possible that you have two `ucsd.edu` usernames, and that `rpwagner` is only one of them. I can only theorize, based on what I'm able to observe, but something has to be distinct between your account at UCSD and your colleague's one.

**Comment by rpwagner** [comment]
After looking at the API docs, I had a feeling this was the case. I'll submit a request and reference this issue. Thanks
