### ISSUE TITLE
globus cli personal endpoint activation is messed up

### ISSUE THREAD

**Issue by denfromufa** [globus/globus-cli#519]
First of all, globusconnectpersonal tool on linux does not work. It fails to find some runtime C++ libraries in COLAB PRO cli:

```
/content# cd globusconnectpersonal-3.1.3/
/content/globusconnectpersonal-3.1.3# su glbs
glbs@e22888e9147f:/content/globusconnectpersonal-3.1.3$ ./globusconnectpersonal -setup
/content/globusconnectpersonal-3.1.3/gt_amd64/bin/register: /tmp/_MEIKWBBf3/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4)
/content/globusconnectpersonal-3.1.3/gt_amd64/bin/register: /tmp/_MEIKWBBf3/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4)
Setup did not complete successfully.
You may want to check /home/glbs/.globusonline/lta/register.log for more information
```

So I tried to use globus-cli python pip package. The problem here is that there is no ONE tutorial to go from setup, account login, endpoint creation and data transfer/download.

Finally I ended up creating personal endpoint to download a dataset from a shared endpoint.
But the activation fails:

```
globus endpoint activate $ep2 --no-browser --web --force --verbose
Autoactivation succeeded with message: Endpoint activated successfully using Globus Online credentials.
```

globus-cli assumes that my endpoint is activated, but the globus website still shows the endpoint not activated and the transfer from shared endpoint is still pending:

![image](https://user-images.githubusercontent.com/7870949/107060183-48456a80-679c-11eb-86c1-7286713df397.png)

**Comment by sirosen** [comment]
> First of all, globusconnectpersonal tool on linux does not work.

Globus Connect Personal is a distinct product from the globus-cli. As such, you should either contact support@globus.org with issues pertaining to it, or you could ask about it on our public discussion mailing list, discuss@globus.org

That said, it looks like you're running into an issue in which the build of the GCP registration script is not as isolated as it should be, and is depending on a system library (which is absent in your case). I suspect running `globusconnectpersonal -setup --no-gui` would work for you, since that avoids using the GUI components. It's possible that would be insufficient, but I don't know offhand.

This is very likely an issue with GCP and we need to follow up on it.
However, I'm not seeing any signs of a CLI bug in what you've reported.

I don't know what `$ep2` is -- you haven't specified -- but it's an endpoint which responds to autoactivation. That means it's either one of the tutorial endpoints or a GCP install (or something more obscure, which is unlikely). Per the `globus endpoint activate` help text, autoactivation is always tried first unless you explicitly disable it.

I'll go ahead and make a leap here and assume that you ran `globus endpoint create --personal` from the CLI, and that `$ep2` is the ID from that command.
That creates an endpoint definition, but it does not install or run globus connect personal.
For fully automated endpoint creation, you would need to pass the setup key from that command to GCP, which allows you to perform a non-interactive setup process.
`globus endpoint create --personal` does not replace GCP setup. It's a distinct command.

> globus-cli assumes that my endpoint is activated

That's not what's happening. You're running the activation command, and it's making an autoactivation request which succeeds.
Autoactivation _always_ succeeds on GCP endpoints, even ones which haven't been setup yet.

The screenshot you've shown indicates that you have a partially setup GCP. The text you see in the webapp saying the endpoint "needs activation" is an unfortunate word choice. It's referring to the fact that you haven't run the GCP setup process yet. The "GCP Key" mentioned there is the setup key which can be obtained explicitly with `globus endpoint create --personal` or automatically by the interactive GCP setup process.

---

What you need is to get GCP actually setup and running. Activation is not the part of the process that has broken down here, and the CLI behavior does not appear to be at fault.
Getting GCP to behave properly in your environment (possibly by installing `libstdc++6` or a similarly named package for your distribution) is the issue that needs resolution.

I'm also going to follow up with our webapp team and ask them to at least consider changing the word choice from "activation" to "requires setup" or similar on that page.

However, there's nothing for the CLI to do. Closing.
