### ISSUE TITLE
Installation documentation issue.

### ISSUE THREAD

**Issue by MCT-MIT-RCP** [globus/globus-cli#528]
The documentation for the globus-cli says that for the installation instructions, go to [https://docs.globus.org/cli/](https://docs.globus.org/cli/) which has a _minor_ 'instruction' section that says:

---

_Installation_

_We enthusiastically recommend using pipx to install the Globus CLI. It provides an isolated environment to keep your CLI installation running smoothly, and it’s resilient to changes in your system’s python installation. An example workflow for installing and managing the CLI would be:_

---

Which does _not_ include an alternative to the "enthusiastically recommended" (recommended != required) method of installation. (The example doesn't offer any choice either.)

If the `pipx` solution is the only choice, please say so.
Otherwise, please offer installation instructions that don't depend on `pipx`.

Thanks all!

**Comment by sirosen** [comment]
We found the previous instructions -- which were quite long -- confused many users. That is why the installation section is so minimal.

The `globus-cli` is a python package available from pypi.
You can install it with `pip`:
```
pip install globus-cli
```

Which means that anywhere that `pip` works, `globus-cli` is installable.

However, because `pipx` covers installation into a virtualenv, symlinking from `~/.local/bin/` (regardless of where `site.USER_BASE` is), and `PATH` manipulation, we strongly recommend that most users use it.

I'll see to it that we amend the docs to note `pipx` first and `pip` secondarily, but I don't believe that we want to restore the verbose instructions for creating a virtualenv and symlinking to it in order to get an isolated install. Users either have enough knowledge and expertise to do this themselves based on the fact that it's a pip package, or they should use `pipx`.

**Comment by sirosen** [comment]
It took a bit longer than I had hoped, but we've updated our docs to include `pip` as an alternative for installation.

You can see the new docs live on the site.
