### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by bsmith030465** [globus/globus-cli#552]
Not sure if this is really an issue or a problem at my end. 

I used globus last year, and before attempting to start globus, I updated it and then tried to login in (new terminal window after updating). Here is what I get:

    node00:[~] % globus --version
    Installed version:  2.1.0
    Latest version:     2.1.0

    You are running the latest version of the Globus CLI
    node00:[~] % globus login
    Globus CLI Error: A Globus Error Occurred.
    error_type:       GlobusConnectionError
    message:          ConnectionError on request

I tried to globus FAQ/google/look up on stackoverflow the error, but couldn't find any help. Is there anything I can do to check if my installation is ok, or anything else?

thanks!

**Comment by sirosen** [comment]
If `globus --version` is working, then your install is probably fine.

I would guess that what happened is that the initial communication with `https://auth.globus.org` failed. Such failures are not retried -- although they will be in the upcoming globus-cli v3.

My first question is whether or not the failure persists. Was this a one-time error, or does it happen consistently?
If it happens every time you try to run `globus login`, but you otherwise have internet connectivity, then you might have a firewall or other network device interfering with the traffic.

What does `curl https://auth.globus.org/p/whoami` give you as a response? It should give you something similar to this unauthorized error response:
```
{"errors": [{"title": "Unauthorized", "code": "UNAUTHORIZED", "id": "ea272abe-6b8d-44d9-9ad1-7d360025357c", "status": "401", "detail": "Call must be authenticated"}], "error": "unauthorized", "error_description": "Unauthorized"}
```

**Comment by sirosen** [comment]
I'm happy to investigate this further -- either here or via support@globus.org -- but absent more info, I'm going to assume this was resolved.

CLI v3 was released a couple of weeks ago and should improve related behaviors with automatic retries, so you may want to upgrade for that reason, if not for others.
