### ISSUE TITLE
cryptography >= 3.4.1 needed

### ISSUE THREAD

**Issue by nathanweeks** [globus/globus-cli#562]
I just installed globus-cli==3.0.0, and observed the following error (with cryptography 3.1.1):

```
$ globus ls
Traceback (most recent call last):
...
  File "/home/user.name/.local/lib/python3.8/site-packages/globus_sdk/services/auth/response.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.rsa import RSAPublicKey
ImportError: cannot import name 'RSAPublicKey' from 'cryptography.hazmat.backends.openssl.rsa' (/home/user.name/.local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/rsa.py)
```

setup.py currently specifies cryptography >= 1.8.1:
https://github.com/globus/globus-cli/blob/0c458d9409b95d84c91b8f218b983c080e74b6f3/setup.py#L57

This error is resolved by installing cryptography >= 3.4.0:
https://github.com/pyca/cryptography/commit/6a8c0b55b99f95e1fcc8bb9c2b03fd9158d2081e#diff-97598491194e5ffd150e82dea4ddb874833c27432477fada5ef1bc9990c4b70fR33

though cryptography >= 3.4.1 is needed to avoid the subsequent error introduced in cryptography==3.4.0:
https://github.com/pyca/cryptography/issues/5756

**Comment by sirosen** [comment]
Hi! Yes, I also ran into this issue while double-checking the behavior of the new version when upgrading an older install.

I have this filed in the SDK here: https://github.com/globus/globus-sdk-python/issues/481

I'm right now working through figuring out the minimal version of `cryptography` we can actually support. We'll then declare that as part of the `globus-sdk` package, and update the dependency here.
Version 3.0.1 of the CLI will be out, probably in a few hours, with the fix.

In the meantime, a fresh install (e.g. `pipx reinstall`) will get anyone who runs into this up and running.

**Comment by sirosen** [comment]
Just a quick follow-up on this. I thought these two things were the same issue, but they are not quite identical.
In the case of globus/globus-sdk-python#481 , we're dealing with a version of `cryptography` which is too old.

However, this appears to be a problem specifically with `cryptography==3.4.0`. I'm going to specify that we not use that version, since it's known to be bugged with `!=3.4.0` in the SDK requirements data.

@nathanweeks, thanks for linking to that `cryptography` issue. It helped a lot in terms of understanding what's going on.

**Comment by sirosen** [comment]
v3.0.1 is now on PyPI. From my testing, this appears to be solved, but please let me know if there are any ongoing issues with the `cryptography` dependency spec.
