### ISSUE TITLE
Batch mode file parsing: unable to ctrl-D or <EOF>

### ISSUE THREAD

**Issue by jlaura** [globus/globus-cli#580]
Globus CLI Version: 3.1.2
Command: `globus transfer $local $caldera --label "cli_batch" --batch ctx_for_globus.txt`
Result:
```bash
Enter transfers, line by line, as

    [--recursive] [--external-checksum TEXT] SOURCE_PATH DEST_PATH

Lines are split with shlex in POSIX mode:
  https://docs.python.org/library/shlex.html#parsing-rules
Terminate input with Ctrl+D or <EOF>
```

where ctx_for_globus.txt is 125k lines in the form
```
fullpathA fullpathB
fullpathA fullpathB
```

Expected behavior: From the docs it looks like passing the text file with full paths should work without any issue in this version. I tried adding an empty newline at the end of the text file, but the result is the same. I tested the text file using shlex.split() and it splits on the space character as expected. Perhaps I am missing something in the docs or is this a bug?

**Comment by jlaura** [comment]
I am going to close - I realized that the message above prints to the terminal and then no output is returned while the program sets up the process. A task ID is properly returned once waiting a sufficiently long amount of time.

**Comment by sirosen** [comment]
Thanks for reporting this. I'm going to open a follow-up because there is actually a bug here!

In v3.0, we switched from `--batch` taking data from stdin to having it take in a filename. However, we didn't remove this bit of info printing, which was important in previous versions because it told users how to stop providing input if they wanted to use `--batch` interactively.
