### ISSUE TITLE
Transfer: is "profile -n off" relevant in the new CLI?

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#61]
- Existing CLI provides a way to turn off task notifications. Is this relevant in the new cli?

**Comment by sirosen** [comment]
There is no API call that I know of which can alter your notifications, but I would like one.
`profile -n off` is obviously not a good name for it in the new world.

I'd like `globus transfer notify on` and `globus transfer notify off` or similar, if we add the relevant API call.

**Comment by sirosen** [comment]
Note that since `globus transfer` is now a command, not a group, the previous name recommendations are not relevant.
It's not at all clear to me how/where we would fit in service-scoped commands with a non-service oriented command structure, so I'm not sure what we could call these commands.

`globus task notifications` seems pretty awkward, but it's the best I can come up with.

**Comment by sirosen** [comment]
Per internal discussions, we aren't going to make a profile API.
Superseded by #368
