### ISSUE TITLE
Transfer: async-transfer default sync-level

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#67]
Right now `--sync-level` is required and defaulting to `mtime`. Is this what we want?

Web app defaults to sync "off" but if turned on, the initial selection is `checksum`.

**Comment by sirosen** [comment]
I selected `mtime` because I thought that sync-level was _required_ by the API.
Of the available sync levels, that and `checksum` are the only two "sensible defaults".
That decision should be viewed as totally non-binding.

I think there's no good way of having a default of no-sync _and_ having a default sync level when enabled with only one option. Options with optional values are very bad, and I don't think that's the way to do it.

We could do two options: `--sync` and `--sync-level` where `--sync-level` implies `--sync`.
So,
 - `globus transfer async-transfer --sync` does a `sync_level=checksum` transfer
 - `globus transfer async-transfer --sync-level=mtime` does a `sync_level=mtime` transfer
 - `globus transfer async-transfer --sync --sync-level=mtime` does a `sync_level=mtime` transfer

An option that I don't like (because it seems awfully picky) is to not allow `--sync-level` without `--sync`.

The other approach of note, which is less ambiguous but a little bit more verbose in some cases, is to not support a "default sync level" and make `--sync-level` (with a required value) the only supported option.
So, for the above,
 - `globus transfer async-transfer --sync-level=mtime` does a `sync_level=mtime` transfer
 - `globus transfer async-transfer --sync-level=checksum` does a `sync_level=checksum` transfer

and that would be it.

**Comment by jaswilli** [comment]
Closed via https://github.com/globus/globus-cli/pull/94/commits/2844f71e0f35078351439cd139685244d301896a (sync level is off by default and available with `--sync-level`)
