### ISSUE TITLE
Globus Examples

### ISSUE THREAD

**Issue by rpwagner** [globus/globus-cli#679]
Hi @sirosen, 

I wanted to touch base with you about the post I made today to Globus Discuss. This goes back to the conversation we had when the [automation examples](https://github.com/globus/automation-examples) were being created, about how to handle community contributions.

I'm got a few (maybe several) end-to-end examples of how to do things for various use cases--when everything is mostly working. I.e., useful demo, teaching, and sys admin script references. These are coming from my work with projects at UCSD, and sharing them publicly is the best way for folks here to find them.

The examples largely build on the Globus Python SDK and use the command line so that it's easy for someone to both read and run them. Which is why I'm dropping this note here because I'm certain there's a ridiculously long wish list for the Globus SDK and CLI that include some of the things I'll be covering. And I fully appreciate the difference between me putting out script with crappy error handling that avoids edge cases compared to what the supported releases need to achieve.

With that framing, here are my intentions as I put these out in the world.

## Vulnerabilities

If you see something egregiously wrong, particularly regarding the handling of tokens, permissions, roles, etc., please let me know. I don't expect anyone to vet or review these examples, but I will take seriously any reports of a potential risk to someone using them.

## Deprecating Examples

When the CLI or some other supported tool from Globus add the same functionality, I'll update my examples to reference it, or even remove the example. This is the part about the SDK and CLI roadmap. I know some of these things will be coming; for now, just treat the examples as a way for the Globus community to adopt product features as the features go from the API, to the SDK, to the CLI.

## Feel Free to Reuse

If anything in an example looks useful, please feel free to reuse it, I would be honored. Realistically, you're not going to find the actual code useful, but maybe a feature will be worth implementing. For example, I think the abiltity to [pass the client ID and secret via a file](https://rpwagner.github.io/notes/2022/09/16/globus-https-put.html#confidential-client) is a good addition to [using environment variables](https://docs.globus.org/cli/environment_variables/#client_credentials_with_globus_cli_client_id). I've started looking at the Globus CLI code to see how to add the option through a pull request, so we'll see if I can contribute directly. 

Likewise, for @vasv and @lliming I'd be glad to see these included in training materials, blog posts, or other sharing if it's worthwhile from your perspective. However, to my comment about about where to host these, I chose not to do a pull request to the automation examples repo or elsewhere. I think it's better to see if how the Globus user community responds to the examples and if it results in a Globus- or community-managed space for contributions.

## Thanks

Finally, thanks for your work on everything that makes these possible.

Let me know if you have any feedback. I figure we can use this issue to discuss things and close when there's a consensus.

--Rick

**Comment by vasv** [comment]
Thanks, Rick! Contributions like this are always welcome. We can certainly include pointers in training materials.

Cheers,
Vas

**Comment by sirosen** [comment]
Although I'm in theory happy to discuss, I've closed this as it isn't really well formed as an issue. It's not a bug, enhancement request, etc.
Phrased otherwise: this is being closed as not having criteria for being closed.

If you wanted, you could repost as a discussion ( https://github.com/globus/globus-cli/discussions ), but I'll be honest that I have pretty limited time these days to engage. (Discussions via discuss@globus.org are pretty limited as well, and if you're active on and watching that list you'll see that I have pulled back my level of responsiveness there significantly.)

---

Within this, there is an item which I'm going to extract into a feature request, which is that we support the ID and secret via a file. I'm a bit hesitant to try to prioritize that, as I think the current interface _works_ and my focus goes first and foremost to the things which _don't work_, but that's just how the plate-spinning goes. I'll put in the issue -- I just want to be clear that that should not read as a promise that it will happen soon.
