### ISSUE TITLE
Transfer: missing `async-delete` options

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#69]
- `label` (set)
- `unsafe`

**Update**
`--label`` implemented in https://github.com/globus/globus-cli/pull/93.

Unsure if we're going to implement `unsafe` as a client-side feature.

**Comment by jaswilli** [comment]
@karlito-go As far as I can tell there's no way to pass `unsafe` through the transfer-api, so I don't think we'll be able to implement this behavior in the SDK/CLI. Am I correct?

**Comment by karlito-go** [comment]
yes, t-api has always set confirmed_unsafe=True.

You could do it locally pretty easily though:
    # These are allowed only with --unsafe
    if path in ("/*", "//*", "/~/*", "/~/.*", "/~/*.*"):
        m = "Unsafe delete path '%s'.  Use --unsafe to override."

But, thats a product mgmt question as to how useful it is.

**Comment by jaswilli** [comment]
Right, I wanted to see exactly what `unsafe` did so I found that part where it was actually implemented. Personally, I'm not sure it's worth duplicating this logic outside of Transfer itself--it seems like it'll just end up being a maintenance headache.

I'll let other people weigh in on that though. Thanks for the info!

**Comment by sirosen** [comment]
As an interesting related note, zsh provides this "helpful" prompt when you `rm *`:
```shell
$ rm *
zsh: sure you want to delete all the files in /tmp/rm-test [yn]? y
```

Link for full doc on [RM_STAR_SILENT](http://zsh.sourceforge.net/Doc/Release/Options.html#index-RMSTARSILENT).
Personally, I find that behavior is usually annoying, but very occasionally makes you take another look at what you've entered.
The adjacent option, `RM_STAR_WAIT`, is clingy and overprotective, by contrast.

I would sooner do what ZSH does and apply the prompt (with available override flag) on all paths ending in a raw `*`, rather than trying to replicate the current CLI behavior.

**Comment by sirosen** [comment]
I opened #129 to replace this.
