### ISSUE TITLE
Login: add support for "local http server" mode

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#75]
- Reference implementation can mostly be copied over from native-app-examples repo
- Provide a way to detect cli is running in a remote session so feature can be disabled
- Should be a way to toggle feature on/off

This stuff will mostly be implemented in the SDK to be leveraged in the CLI.

**Comment by sirosen** [comment]
> This stuff will mostly be implemented in the SDK to be leveraged in the CLI.

It will? I don't really think that it belongs there at all.
The SDK is the thing that we have a much stronger commitment to support as an "all terrain" package, compatible with a vast variety of scenarios. As such, I think it should be kept minimal and well-focused.

If we were doing a `globus-contrib` style thing, this would definitely be a feature I would target for `globus-contrib`.

**Comment by sirosen** [comment]
We agreed that this is okay to add as long as it doesn't require any changes to `NativeAppAuthClient` or the corresponding flow.

The current plan is for the local server to provide it wrapped in an object handle.
We can provide `.shutdown()` on it as a cleanup, but I would also like to see this implemented as a context manager so that we can have shutdown implicitly called via `__exit__`.

**Comment by sirosen** [comment]
Moving this to 1.0 per PM request.

**Comment by sirosen** [comment]
@aaschaer Can you take a crack at this?

Jason already made a prototypical version in https://github.com/globus/native-app-examples
It includes solutions to some of the tricky bits, like [detecting local vs. remote sessions](https://github.com/globus/native-app-examples/blob/master/utils.py#L37).
