### ISSUE TITLE
cant download file to local PC using globus transfer when using 'file://" as DEST_ENDPOINT_ID[:DEST_PATH]

### ISSUE THREAD

**Issue by Guy-Shtainer** [globus/globus-cli#762]
As described in the title, I am trying use the globus-cli to download a file to a local host. I have connected to the globalconnect servers using "globus login" and able to find my file using the "globus ls". I cant install the globus connect personal package on my ubuntu machine since it has aarch64 architecture. So I tried using this line of code suggest by Chat-GPT:
globus transfer SOURCE_ENDPOINT_ID:/path/to/source/file "file:///path/to/destination/file"

It claims that doing so allows me to download the file directly to a path in my machine, but I get the following error:
Error: Invalid value for 'DEST_ENDPOINT_ID[:DEST_PATH]': 'file' is not a valid UUID.

Please help!
Thanks.

**Comment by aaschaer** [comment]
Unfortunately Chat-GPT has misled you, submitting a Globus Transfer requires both ends of the transfer to be configured as Globus endpoints/collections, which is why their uuids are required by the `globus transfer` command.

Even if you can't install Globus Connect Personal or Globus Connect Server on your machine, if the files you are trying to access are hosted on a Globus Connect Server v5, you may be able to access them over HTTPS. The CLI does not yet support HTTPS downloads, but the filemanager on the Globus webapp does: https://app.globus.org/file-manager

Closing this issue as a can't-fix, but will note this as a usecase for HTTPS download in the CLI to help prioritize that work.
