### ISSUE TITLE
Allow additional flags to be passed in addition to --batch

### ISSUE THREAD

**Issue by jbellino-usgs** [globus/globus-cli#863]
I'm trying to submit a batch transfer request and would like to label the job so I can use this in a production workflow. Currently the behavior of `globus transfer --batch batchfile.txt src dst` works as expected, but yields a job with a generic name. The addition of the `--label` flag seems to confuse globus:

```
(wrf-python)~ SRC=asdfasdf-src-end-point-asdfasdf:/input/metgrid/2004
(wrf-python)~ DST=asdfasdf-dst-end-point-asdfasdf:/input/metgrid/2004
(wrf-python)~ LABEL='My Label'
(wrf-python)~ globus transfer --label $LABEL --batch batchfile.txt $SRC $DST

Usage: globus transfer [OPTIONS] SOURCE_ENDPOINT_ID[:SOURCE_PATH] DEST_ENDPOINT_ID[:DEST_PATH]

Error: Invalid value for 'SOURCE_ENDPOINT_ID[:SOURCE_PATH]': 'Label' is not a valid UUID.
```

Currently using globus version 3.18.0

**Comment by sirosen** [comment]
Hi there!

This is actually not a bug. Because you didn't quote your `$LABEL` variable, shell word splitting applied.
What the globus-cli saw was this:
```
globus transfer --label My Label ...
```

Meaning `--label=My` and a first positional argument of `Label`.

You can solve it easily by putting double-quotes around your `$LABEL` usage, like so:
```
globus transfer --label "$LABEL" --batch batchfile.txt "$SRC" "$DST"
```

I recommend double-quoting all shell variables as a habit -- it will prevent surprises like this with the globus-cli and other commands.

**Comment by jbellino-usgs** [comment]
Thanks for that, I do have my production scripts setup that way but had put the `--batch` flag after the src and dst positional arguments which was causing the command to hang. During testing I got lazy and when I moved things around that's when I started getting this other problem. A job just went through with my patched shell script and it looks good!
