### ISSUE TITLE
ORCID login

### ISSUE THREAD

**Issue by leorrose** [globus/globus-cli#874]
When I try to login via ORCID on I get a 500 error:

![image](https://github.com/globus/globus-cli/assets/44137602/cd6954aa-5ef8-447e-b9c6-0e01a3cd90b8)

Login using google\email works but only ORCID doesn't.

**Comment by sirosen** [comment]
Hi there; thanks for reporting this.
Unfortunately, there's actually no resolution (as far as I can see, within reason) within the Globus CLI for this issue. It's a limitation of the ORCID service which causes a failure due to an interaction with Globus Auth. When the data sizes being encoded and passed between the two services in the form of query params gets too large, this happens.

You'll see this with the CLI more easily than the Globus WebApp (app.globus.org) because the CLI is trying to satisfy a different user experience -- one with the fewest possible number of login flows. As such, we need to request all of the scopes which we know we will need from the service up-front. That inflates the data sizes involved and makes it more likely to be reached (although it can be reached with any client in the right scenarios). app.globus.org can request fewer scopes because redirecting a user to an additional incremental login flow within the browser is a lot simpler and "cheaper" than doing it from a CLI.

It's possible that the Globus Auth team knows of workarounds for this, and I would encourage you to submit this to support@globus.org so that we can get you responses and assistance from that team. Sadly, there's not a clear improvement to the CLI behavior to accommodate this, so I'm going to close and hope that you can find a workaround via our support ticketing channels.
