### ISSUE TITLE
Add a dry-run mode for transfer submission?

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#91]
#89 in particular got me thinking about this.

When submitting transfer and delete tasks, there's potential with the CLI to produce very elaborate flows whose actual transfer semantics could start to become lost to the scripting user.
It would be nice to provide some kind of dry-run output (which doesn't have to look like our ordinary output) that at least describes the tasks that the user is submitting on stdout.

That way, if I've written my scripts well, I can have something like this:
```shell
#!/bin/bash
...
GLOBUS_CLI_ASYNC_TRANSFER_OPTS="--dry-run --sync-level=checksum"
GLOBUS_CLI_ASYNC_DELETE_OPTS="--dry-run --recursive"
...
```

I'm not at all suggesting that we support these env vars ourselves, but it's a common pattern and plays well into this idea.

**Comment by corpulentcoffee** [comment]
Yes please. I very often `print()` the submission data and return when debugging these two commands, and this would be very useful.

**Comment by sirosen** [comment]
I wrote a quick and dirty version of this to play with. The one question that arose there was output format: what does the text output and JSON output look like?

JSON is kind of easy -- just dump the submsision data directly.
For now, I'm doing that as the text output as well, but we like to avoid that most of the time.
There are lots of options for text. Is there anything that seems like it would be very good / highly desirable?

**Comment by corpulentcoffee** [comment]
The absolutely most useful thing to dump is the list of paths (or path pairs), since those can come from some combination of batch input and the command arguments, and we have already seen internally that we have gotten confused about what the interactions are.

It wouldn't be "complete" without dumping the other fields (e.g. submission ID, recursive flag, sync level, label, encrypt), though.
